---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  echo = FALSE,
  comment = "#>"
)
library(tidyverse)
library(janitor)
library(maps)
source("R/cheese.R")
```

# Tidy Tuesday - National Cheese Day

<!-- badges: start -->
<!-- badges: end -->

This week's Tidy Tuesday dataset is about cheese! 🧀

Cheese.com has information on over 1,000 cheeses from around the world. 

```{r cheese_map}

world_map <- map_data("world") %>%
  mutate(region = if_else(!is.na(subregion) & region == "United Kingdom", subregion, region)) %>%
  mutate(region = case_when(
    region == "USA" ~ "United States",
    region == "UK" ~ "United Kingdom",
    TRUE ~ region
  ))

cheese_map <- world_map %>%
  left_join(cheese_by_country, by = c("region" = "country"))

no_match <- cheese_by_country %>%
  filter(!country %in% world_map$region)

cheese_map_plot <- ggplot(cheese_map, aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = count), color = "white") +
  coord_fixed(1.3) +
  theme_minimal() +
  scale_fill_viridis_c() +
  labs(
    title = "Cheese by Country",
    fill = "Cheese Count"
  )


plot(cheese_map_plot)


```



```{r texture}
# get the top ten textures from cheese_texture

top_five_texture <- cheese_texture %>% 
  slice_max(count, n = 5) 

common_texture_string <- str_c(top_five_texture$texture, collapse = ", ")
```



The most common types of descriptors for cheese include `r common_texture_string`. 
